<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => '',
    'Address' => '',
    'Are you sure you want to delete this item?' => '',
    'Background Color' => '',
    'Btn Color' => '',
    'Btn Color Hover' => '',
    'Class' => '',
    'Color' => '',
    'Content' => '',
    'Create Tb Blog' => '',
    'Create Tb Curiculum' => '',
    'Create Tb Facilities' => '',
    'Create Tb Faculty' => '',
    'Create Tb Structure' => '',
    'Created At' => '',
    'Created By' => '',
    'Curiculum Type ID' => '',
    'Custom Logo' => '',
    'Default Logo' => '',
    'Delete' => '',
    'Desc' => '',
    'Division ID' => '',
    'Educational Background' => '',
    'Email' => '',
    'Favicon' => '',
    'I Class' => '',
    'ID' => '',
    'Image' => '',
    'Is Enabled' => '',
    'Language ID' => '',
    'Logo' => '',
    'Maps' => '',
    'Message' => '',
    'Name' => '',
    'Navbar Color' => '',
    'Number' => '',
    'Pause Social Proof' => '',
    'Reset' => '',
    'Save' => '',
    'Search' => '',
    'Slug' => '',
    'Social Proof' => '',
    'Socialmedia' => '',
    'Structure ID' => '',
    'Tb Blogs' => '',
    'Tb Curiculums' => '',
    'Tb Facilities' => '',
    'Tb Faculties' => '',
    'Tb Structures' => '',
    'Testimony' => '',
    'The requested page does not exist.' => '',
    'Time Social Proof' => '',
    'Timestamp' => '',
    'Title' => '',
    'Update' => '',
    'Update Tb Blog: {name}' => '',
    'Update Tb Curiculum: {name}' => '',
    'Update Tb Facilities: {name}' => '',
    'Update Tb Faculty: {name}' => '',
    'Update Tb Structure: {name}' => '',
    'Updated At' => '',
    'Updated By' => '',
    'Url' => '',
    'User ID' => '',
    'Vision Mision' => '',
    'Wa Direction' => '',
];
